# netstat -ano | findstr 8080
# taskkill /F /pid [PID]
server:
  url: http://localhost
  port: 8080
logging:
  level:
    com.everyt: debug
jwt:
  header: Authorization
  secret: ZXZlcnl0LW5leHRlYS1wcmV0dHktbXVjaC1iYXNlLTY0LWNvZGUtYmVmb3JlLWVuY29kZS1qd3Qtc2VjcmV0LWNvZGUtc2VjcmV0LWZpbmFsbHk
  expirationSeconds: 86400
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    diver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    hivernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true