server:
  # PORT 설정
  url: http://localhost
  port: 8080
 
spring:

  main:
    allow-bean-definition-overriding: true
    
  h2:
    console:
      enabled: true
      path: /h2-console
      
  datasource:
    # url: jdbc:mysql://localhost:3306/nextea_db
    # username: nextea
    # password: 1234Qwer
    # driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:h2:mem:testdb
    diver-class-name: org.h2.Driver
    username: sa
    password:
  # JPA 설정
  
  jpa:
    defer-datasource-initialization: true
    hivernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        # Dialect 설정
        dialect: org.hibernate.dialect.H2Dialect
        # Hibernate가 실행하는 모든 SQL를 Console에 출력한다.
        show_sql: true
        # Console에 출력되는 JPA 실행 Query를 가독성 있게 표현한다.
        format_sql: true
        # Debugging이 쉽도록 SQL 이외 추가적인 정보를 출력한다.
        use_sql_comments: true

logging:
  level:
    com.everyt: DEBUG
    
jwt:
  header: Authorization
  secret: ZXZlcnl0LW5leHRlYS1wcmV0dHktbXVjaC1iYXNlLTY0LWNvZGUtYmVmb3JlLWVuY29kZS1qd3Qtc2VjcmV0LWNvZGUtc2VjcmV0LWZpbmFsbHk=
  token-validity-in-seconds: 86400